services:
  redis-stack:
    # Includes Redis server with RedisJSON, RediSearch (vector), TimeSeries, Streams and RedisInsight
    image: redis/redis-stack:latest
    container_name: ai-wellness-redis
    ports:
      - "6379:6379"  # Redis server
      - "8001:8001"  # RedisInsight UI
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
