services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: ai-wellness-redis
    ports:
      - "6379:6379"      # Redis port
      - "8001:8001"      # RedisInsight port
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
